# Generated by Django 5.2.17 on 2026-09-14 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('al dia', 'Al día'), ('moroso', 'Moroso')], max_length=20)),
                ('resultado', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
